# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6fca41598d7182b57acd75a8ee218bdac420addf704e555705d5bcdfc10e01fae0fb8211934947a0b61fbda3825706fbbea006a18d0170024e09537b25b25a65

test:
  secret_key_base: 650011dc2514f418b7d99a2ce9e40846af49be16cc1a08c039f2592252b713e051bf8efce59390385632a3ebdd4a8b7e059f935c0c34ae0c72ce2d131a8dc814

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
